### ISSUE TITLE
ErrImagePull after creating pod

### ISSUE THREAD

**Issue by bormansquirrel** [upmc-enterprises/registry-creds#31]
Hello,

I'm trying to use your app to pull images from ecr private registry. The registry is working when I pull from docker on my local machine using asw cli as usual.  I'm getting ErrImagePull error every time I try to create a pod that needs image from that registry:
```
$ kubectl get pod my-pod
NAME      READY     STATUS         RESTARTS   AGE
my-pod     0/1       ErrImagePull   0          8s
```
I've followed the next steps:
1. Edit k8s/secret.yaml file with my obscured aws credentials (base64)
2. Create  secret:
`$ kubectl create -f k8s/secret.yaml`
3. Activate minikube awsecr-creds addon
```
$ minikube addons list
- dashboard: enabled
- kube-dns: enabled
- heapster: disabled
- ingress: disabled
- awsecr-creds: enabled
- addon-manager: enabled
```
4. Create rc with region parameter attached as an argument args:
 "--aws-region=eu-west-1"
`$ kubectl create -f k8s/replicationController.yaml`

5. Create my-pod with image parameter pointing to my ecr
`$ kubectl create -f mypod.yaml`
```
apiVersion: v1
kind: Pod
metadata:
    name: my-pod
spec:
  containers:
  - name: my-pod
    image: XXXXXXXXXX.dkr.ecr.eu-west-1.amazonaws.com/my-pod:latest
```

When I describe my-pod I can see that effectively is a credentials issue:
```
Failed to pull image "XXXXXXXXXX.dkr.ecr.eu-west-1.amazonaws.com/my-pod:latest": unauthorized: authentication requiredals issue:
```
Can you see anything wrong on the process I'm following?

Thanks

**Comment by stevesloka** [comment]
Are any logs from the add-on that are helpful?

**Comment by callmeradical** [comment]
I am going to go out on a limb and say that you didn't set your region in the RC 

```bash
$ kubectl edit rc registry-cress --namespace=kube-system
```

Go ahead and add a new ENV for awsregion and set it to eu-west-1

**Comment by turgayozgur** [comment]
The "registry-creds" addon creates new credential named "**awsecr-cred**" for Default namespace. Your deployment yaml should be like this:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: [application-name]
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: [application-name]
    spec:
      imagePullSecrets: # <-- Important bit here. cred name should be awsecr-cred
        - name: awsecr-cred
      containers:
        - name: [application-name]
          image: [accountid].dkr.ecr.eu-central-1.amazonaws.com/[imagename]:[version]
          ports:
          - containerPort: [e.g: 5000]
```
Important Steps:

1- Don't use `echo -n "secret-key" | base64` to encode your aws credentials. Use online tools for this.
2- Your credentials should not start with " and should not end with "
3- If you want to use diffrent location for pulling images from aws ecr, add "aws-region: [base64 region string]" after aws-account variable on secret.yaml. And add this lines to end of the replicationController.yaml, if it is not exist.

```yaml
- name: awsregion
   valueFrom:
     secretKeyRef:
       name: registry-creds
       key: aws-region
```
#36
