### ISSUE TITLE
Cannot pull images from AWS ECR: no basic auth credentials (v0.27.0 minikube)

### ISSUE THREAD

**Issue by ptaillard** [upmc-enterprises/registry-creds#65]
**Environment**:

- **Minikube version** : 0.27.0
- **OS** (e.g. from /etc/os-release): MacOS 10.12.6 High Sierra
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): v0.26.0
- **Install tools**: homebrew

**What happened**:
I cannot pull images from the ECR registry: "no basic auth credentials" error

**What you expected to happen**:
I expected to pull the image from the ECR registry after having configured registry-creds with my ID, KEY, TOKEN and AWS Region, and activating the registry-creds addon and using PullSecrets

**How to reproduce it** (as minimally and precisely as possible):
 `minikube start`
`minikube addons configure registry-creds` => configure only with AWS ECR
`minikube addons enable registry-creds`
`kubectl create -f deployment.yaml`
=> The error occured: cannot start the container due to **no basic auth credentials** error.

`kubectl get secrets --all-namespaces` => we can see that the secret created is in **kube-system** and called **registry-creds-ecr**. I never found the **awsecr-cred** name for the secret as mentioned in the documentation https://github.com/upmc-enterprises/registry-creds

deployement.yaml content:
> apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: <APP>
    spec:
      containers:
        - name: adserver-test
          image: <MY_ACCOUNT_ID_REMOVED_HERE>.dkr.ecr.us-east-1.amazonaws.com/<IMAGE_TO_PULL>:latest
          command: ["/bin/bash"]
          env:
            - name: TMN_ENVIRONMENT
              value: "qa"
      imagePullSecrets:
        - name: registry-creds-ecr

**Output of `minikube logs` (if applicable)**:

> May 23 09:53:31 minikube kubelet[3443]: W0523 09:53:31.388519    3443 kubelet_pods.go:878] Unable to retrieve pull secret default/registry-creds-ecr for default/adserver-deployment-654f4668bf-l97n8 due to secrets "registry-creds-ecr" not found.  The image pull may not succeed.

> May 23 09:53:31 minikube kubelet[3443]: I0523 09:53:31.388628    3443 kuberuntime_manager.go:513] Container {Name:adserver-test Image:<MY_ACCOUNT_ID_REMOVED_HERE>.dkr.ecr.us-east-1.amazonaws.com/adserver:latest Command:[/bin/bash] Args:[] WorkingDir: Ports:[] EnvFrom:[] Env:[{Name:TMN_ENVIRONMENT Value:qa ValueFrom:nil}] Resources:{Limits:map[] Requests:map[]} VolumeMounts:[{Name:default-token-27gpt ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount SubPath: MountPropagation:<nil>}] VolumeDevices:[] LivenessProbe:nil ReadinessProbe:nil Lifecycle:nil TerminationMessagePath:/dev/termination-log TerminationMessagePolicy:File ImagePullPolicy:Always SecurityContext:nil Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.

> May 23 09:53:32 minikube kubelet[3443]: E0523 09:53:32.229556    3443 remote_image.go:108] PullImage "<MY_ACCOUNT_ID_REMOVED_HERE>.dkr.ecr.us-east-1.amazonaws.com/adserver:latest" from image service failed: rpc error: code = Unknown desc = Error response from daemon: Get https://<MY_ACCOUNT_ID_REMOVED_HERE>.dkr.ecr.us-east-1.amazonaws.com/v2/adserver/manifests/latest: no basic auth credentials

> May 23 09:53:32 minikube kubelet[3443]: E0523 09:53:32.229585    3443 kuberuntime_image.go:51] Pull image "<MY_ACCOUNT_ID_REMOVED_HERE>.dkr.ecr.us-east-1.amazonaws.com/adserver:latest" failed: rpc error: code = Unknown desc = Error response from daemon: Get https://<MY_ACCOUNT_ID_REMOVED_HERE>.dkr.ecr.us-east-1.amazonaws.com/v2/adserver/manifests/latest: no basic auth credentials

> May 23 09:53:32 minikube kubelet[3443]: E0523 09:53:32.229627    3443 kuberuntime_manager.go:733] container start failed: ErrImagePull: rpc error: code = Unknown desc = Error response from daemon: Get https://<MY_ACCOUNT_ID_REMOVED_HERE>.dkr.ecr.us-east-1.amazonaws.com/v2/adserver/manifests/latest: no basic auth credentials

> May 23 09:53:32 minikube kubelet[3443]: E0523 09:53:32.229648    3443 pod_workers.go:186] Error syncing pod 1d7cad94-5e6f-11e8-962c-0800278cf469 ("adserver-deployment-654f4668bf-l97n8_default(1d7cad94-5e6f-11e8-962c-0800278cf469)"), skipping: failed to "StartContainer" for "adserver-test" with ErrImagePull: "rpc error: code = Unknown desc = Error response from daemon: Get https://<MY_ACCOUNT_ID_REMOVED_HERE>.dkr.ecr.us-east-1.amazonaws.com/v2/adserver/manifests/latest: no basic auth credentials"

**Comment by nicroto** [comment]
I am facing the same issue as @erstaples.

@stevesloka do you have any ideas what may've gone wrong? I see a lot of Pull Requests with reasonable changes (the docs changes with info for minikube setup seems quite useful, for example) - is this repo still being supported/developed?

**Comment by stevesloka** [comment]
Hey, @nicroto yes this repo is still maintained, just hasn't needed many updates recently. 

Let me give this a shot, something might have changed upstream with the aws sdk, but I doubt that's really the issue. I had someone else recently use this on `docker-for-mac`'s k8s integration and it worked. 

To confirm you're doing the same steps that @erstaples did to first configure, then enable?

**Comment by nicroto** [comment]
Hey @stevesloka, thanks for the quick reply.

Yes, I am doing the same thing.
```shell
minikube delete
minikube start
minikube addons configure registry-creds
# then I would enter my creds from AWS
minikube addons enable registry-creds
```

Then I would install a helm chart which has a deployment.yaml looking roughly like this:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    app: {{ template "app.name" . }}
    ...
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "app.name" . }}
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecrets }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.internalPort }}
            initialDelaySeconds: 240
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.internalPort }}
          resources:
            ...
      nodeSelector:
        ...
```

and in my values.yaml file I would have:

```yaml
replicaCount: 1
image:
  repository: <omitted my account id>.dkr.ecr.us-east-1.amazonaws.com/<omitted repo name>
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: awsecr-cred
...
```

If it does work on your end - maybe we are making some kind of mistake when entering the creds?
Here is what I do once the `configure` command is called on minikube, for each and every entry:

 1. `-- Enter AWS Access Key ID:`
    * For that I would go to my AWS Developer Console;
    * IAM;
    * Users;
    * click on specific user (with all required permissions enabled/attached to it);
    * Security Credentials Tab;
    * Create Access Key;
    * copy the id.
 2. `-- Enter AWS Secret Access Key:`
    * From the same generated key, I would click "Show" on the Secret value and copy it.
 3. `-- (Optional) Enter AWS Session Token:`
    * I don't enter/paste anything, just press Return.
 4. `-- Enter AWS Region:`
    * I enter `us-east-1a` (both my ECR repo and my cluster are located in this region).
 5. `-- Enter 12 digit AWS Account ID (Comma seperated list):`
    * From the top menu I would click on my username and in the dropdown I choose "My Security Credentials";
    * Then I click Continue To Security Credentials (in the dialog box that shows up);
    * Then I expand the "Account Identifiers" pane in the accordion/panelbar widget;
    * Then I copy the "AWS Account ID" and replace the dashes with commas:
      * `xxxx-xxxx-xxxx` -> `xxxx,xxxx,xxxx`
    * and I paste that in the CLI.
 6. `-- (Optional) Enter ARN of AWS role to assume:`
    * I go to IAM service;
    * Users;
    * Click on the same user I generated the Access Key on;
    * And I just copy the value from the "User ARN" field.
 7. I decline to set up GCE and private docker registry.

**Comment by nicroto** [comment]
@stevesloka Did you manage to check this out?

**Comment by stevesloka** [comment]
Sorry I upgraded minikube and now latest doesn't work. I'll keep troubleshooting, if not I have an older build which should work. 

By the way, what version of minikube are you using? 0.27?

**Comment by nicroto** [comment]
Thanks. I am currently using `0.26.1`. What is the latest version that it works on? I think I am using a feature that isn't available on an earlier version... but I am not sure what that was.

**Comment by ahanoff** [comment]
I had same problem, I added manually secret to default namespace and it started working

**Comment by ahanoff** [comment]
My logs showed me 
> Jul 04 08:19:27 minikube kubelet[2997]: W0704 08:19:27.226152    2997 kubelet_pods.go:878] Unable to retrieve pull secret default/awsecr-creds for default/blabla due to secrets "awsecr-creds" not found.  The image pull may not succeed.

but when I configure addon I found that actually minikube creates 'awsecr-cred' instead of 'awsecr-creds', so I just put name of secret without s and everything is working now.

**Comment by ahanoff** [comment]
@nicroto I didn't get it your step 5 in configure addon. What dashes in your account id? Account id is just 12 numbers, so just type xxxxxxxxxxxx

**Comment by nicroto** [comment]
@ahanoff Maybe this is it. That is why I posted every detail of my setup, so a mistake can be ruled out.
Will check it out and come back with more info. Thanks.

**Comment by sylvain-rouquette** [comment]
@ahanoff doesn't work for me, v0.28.0 with awsecr-cred. I have this log:

Unable to retrieve pull secret default/awsecr-cred for default/data-service-7ccb57c46d-662h7 due to secrets "awsecr-cred" not found

**Comment by ahanoff** [comment]
@sylvain-rouquette can you check if this secret exists using kubectl? It shoud be in kube-system namespace

**Comment by sylvain-rouquette** [comment]
@ahanoff I have registry-creds-ecr running in kube-system, but I get the same error if I set this for imagePullSecrets.

isn't the problem the "default/" at the beginning, shouldn't it be "kube-system/" instead?

**Comment by ahanoff** [comment]
@sylvain-rouquette can you pull image to your local environment using those credentials? Just docker pull. Thanks

**Comment by sylvain-rouquette** [comment]
yes it works locally. now awsecr-cred doesn't show an error anymore. You were right, I had to use awsecr-cred in imagePullSecrets.

But now I have this error: no basic auth credentials.

**Comment by ahanoff** [comment]
You can try kill pod of registry-creds 😄 but I would try reconfigure registry creds again

**Comment by guemues** [comment]
If i run minikube without any driver it continuous giving this error even ingress addon enabled:
`
"caused by: Post https://ecr.eu-west-1.amazonaws.com/: dial tcp: lookup ecr.eu-west-1.amazonaws.com on 10.96.0.10:53: read udp 172.17.0.8:33304->10.96.0.10:53: i/o timeout"`

if i run Minikube with VirtualBox it doesn't give any error.

**Comment by stevesloka** [comment]
Good to hear you got it working @guemues! 

To everyone on this thread, I'm going to close as it seems all issues are ok? If not feel free to open a new one or reopen this one. Thanks!

**Comment by nicroto** [comment]
I am still getting the "no basic auth credentials", even after following @sylvain-rouquette's procedure and having all tools upgraded to latest AND using my Account ID in "xxxxxxxxxxxx" form.

How can I further debug this to give you more info on what's going wrong, here?

Here is a simplification of my deployment that fails to pull an image from ECR:

```yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "chart-name.fullname" . }}
  labels:
    app: {{ template "chart-name.name" . }}
    chart: {{ template "chart-name.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "chart-name.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "chart-name.name" . }}
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: awsecr-cred
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
```
