### ISSUE TITLE
ECR - InvalidParameterException: Invalid parameter at 'registryIds' failed to satisfy constraint

### ISSUE THREAD

**Issue by fooock** [upmc-enterprises/registry-creds#88]
I'm unable to make this to work in a Kubernetes 1.16. My configuration is:

```
apiVersion: v1
kind: Secret
metadata:
  name: registry-creds-ecr
  namespace: kube-system
  labels:
    app: registry-creds
    kubernetes.io/minikube-addons: registry-creds
    cloud: ecr
data:
  AWS_ACCESS_KEY_ID: xxx
  AWS_SECRET_ACCESS_KEY: xxx
  aws-region: xxx
type: Opaque
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: registry-creds
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - get
      - update
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: registry-creds
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: registry-creds
subjects:
  - kind: ServiceAccount
    name: registry-creds
    namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: registry-creds
  namespace: kube-system
```
My deployment file is:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-creds
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: registry-creds
  template:
    metadata:
      labels:
        name: registry-creds
    spec:
      serviceAccountName: registry-creds
      containers:
        - image: upmcenterprises/registry-creds:1.10
          name: registry-creds
          imagePullPolicy: Always
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: registry-creds-ecr
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: registry-creds-ecr
                  key: AWS_SECRET_ACCESS_KEY
            - name: awsregion
              valueFrom:
                secretKeyRef:
                  name: registry-creds-ecr
                  key: aws-region
            - name: awsaccount
              valueFrom:
                secretKeyRef:
                  name: registry-creds-ecr
                  key: aws-account
      volumes:
        - name: gcr-creds
          secret:
            secretName: registry-creds-gcr
```
When the two files are deployed, then the logs from the pod are:

```
time="2020-03-22T03:18:09Z" level=info msg="------------------ [awsecr-cred] ------------------
" 
time="2020-03-22T03:18:09Z" level=info msg="Getting secret; try #1 of 4" 
time="2020-03-22T03:18:09Z" level=info msg="InvalidParameterException: Invalid parameter at 'registryIds' failed to satisfy constraint: 'Member must satisfy constraint: [Member must satisfy regular expression pattern: [0-9]{12}]'
	status code: 400, request id: a2acc201-35df-40c0-8cce-196f02b53e02" 
time="2020-03-22T03:18:09Z" level=error msg="Error getting secret for provider awsecr-cred. Will try again after 5.000000 seconds. [Err: InvalidParameterException: Invalid parameter at 'registryIds' failed to satisfy constraint: 'Member must satisfy constraint: [Member must satisfy regular expression pattern: [0-9]{12}]'
	status code: 400, request id: a2acc201-35df-40c0-8cce-196f02b53e02]" 
```
The secret `awsecr-cred` is empty. Any thoughts on this?
